require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - config/**/*
    - db/**/*
    - config.ru
    - Gemfile
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - bin/bundle

Metrics/MethodLength:
  Exclude:
    - bin/bundle
    - db/**/*

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Exclude:
    - bin/bundle

Rails/Present:
  Exclude:
    - bin/bundle

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
